#!/bin/bash

#su www-data -c "/usr/local/bin/tftriggers"
chown -R www-data:nogroup /usr/torrentflux/.transfers /usr/torrentflux/.processed
chmod -R 775 /usr/torrentflux/.transfers/ /usr/torrentflux/.processed
su sairuk -c "/usr/local/bin/tftriggers"
exit 0
