#!/bin/bash

# Takes Current Directory as Input if not arguement on cli
INPUT=$1

PARFILE=`find ${INPUT} -name "*.par2" -print -quit`

if [ ${PARFILE} ]; then
 echo "Found ${PARFILE}"
 PAR2MISS=`par2repair "${PARFILE}" | grep -o "Repair is not possible."`
 echo $PAR2MISS
 if [ "${PAR2MISS}" ]; then
  echo "PAR2 Repair incomplete, running with output"
  par2repair "${PARFILE}"
  exit 1
 fi
 exit 0
else
 echo "Could Not Locate PAR2 File"
 exit 2
fi

PAR2MISS=""
